// script.js
const jokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
    "Why do programmers hate nature? It has too many bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers hate nature? It has too many bugs!",
    "Why do programmers always get Christmas and Halloween mixed up? Because Oct 31 == Dec 25!",
    "Why do programmers like dark mode? Because light attracts bugs!",
    "Why don't programmers like nature? It has too many bugs!",
    "Why do programmers prefer Halloween over Christmas? Because Oct 31 equals Dec 25!",
    "Why do programmers enjoy dark mode? Because bugs are attracted to light!",
    "Why don't programmers like nature? Too many bugs!",
    "Why did the programmer quit his job? He didn't get arrays!",
    "Why did the programmer leave his job? He couldn't find an array of opportunities!",
    "Why did the programmer give up? He didn't have enough arrays!",
    "Why was the JavaScript developer sad? Because he didn't 'null'ify his emotions!",
    "Why was the programmer's phone always out of space? Too many bugs!",
    "Why did the programmer go broke? He used up all his cache!",
    "Why did the programmer break up with his calculator? They had too many arguments!",
    "Why did the programmer stay up all night? To catch bugs in the act!",
    "Why did the programmer give up his job? He had reached his breakpoint!",
    "Why was the JavaScript developer mad? Because he didn't get JavaScript!",
    "Why do programmers prefer to work at night? Fewer bugs!",
    "Why was the computer cold? It left its Windows open!",
    "Why do programmers hate nature? It's so un-structured!",
    "Why do programmers prefer dark mode? It's easier on the arrays!",
    "Why do programmers hate insects? Too many bugs!",
    "Why was the C# developer so sleepy? He didn't get a proper interface!",
    "Why don't programmers like nature? It's too unpredictable and has no error handling!",
    "Why did the programmer quit? He didn't get arrays of recognition!",
    "Why did the programmer refuse to learn SQL? It had too many queries!",
    "Why did the programmer quit? He had a null-point exception!",
    "Why did the programmer leave his job? He didn't have a good interface with his boss!",
    "Why was the computer cold? Someone left the Windows open!",
    "Why did the programmer ghost his date? He wanted to avoid any commitments!",
    "Why do programmers prefer Halloween? They get to dress up in byte-sized costumes!",
    "Why was the programmer cold? He forgot to close Windows!",
    "Why do programmers hate insects? Too many bugs to handle!",
    "Why do programmers dislike insects? Too many bugs!",
    "Why was the developer always cold? He forgot to close Windows!",
    "Why do programmers stay indoors in spring? It's too much recursion with the bugs!",
    "Why did the programmer give up on his diet? He had too many bytes!",
    "Why did the programmer give up on dieting? Too many bytes!",
    "Why do programmers dislike sunlight? It reveals too many bugs!",
    "Why did the JavaScript developer go broke? He spent all his cache!",
    "Why don't programmers like nature? It's full of bugs!",
    "Why did the computer keep sneezing? It had a virus!",
    "Why did the programmer date a unit test? It was love at first assert!",
    "Why did the programmer give up on love? He had too many unhandled exceptions!",
    "Why did the programmer refuse to go on a date? The chemistry was 'undefined'!",
    "Why do programmers prefer dark mode? It reduces eye 'bugs'!",
    "Why did the programmer start using glasses? To improve his C-vision!",
    "Why do programmers prefer cold weather? It keeps their computers cool!"
];

const facts = [
    "The first computer programmer was a woman named Ada Lovelace.",
    "The first computer bug was actually a real bug - a moth that caused a glitch in a computer in 1947!",
    "The first computer mouse was made of wood!",
    "Ada Lovelace, an English mathematician, is considered the world's first computer programmer. She created the first algorithm designed for Charles Babbage's Analytical Engine.",
    "The term 'bug' to describe a computer defect originated from an actual insect (a moth) found inside a computer by Grace Hopper in 1947.",
    "The first computer virus, 'Creeper,' was created in the early 1970s by Bob Thomas.",
    "The 'Hello, World!' program is a classic introductory program used to demonstrate the basic syntax of a programming language.",
    "Python, a popular programming language, was named after the British comedy show 'Monty Python's Flying Circus.'",
    "The concept of Object-Oriented Programming (OOP) was first introduced by Alan Kay in the 1960s.",
    "The ENIAC (Electronic Numerical Integrator and Computer) was the world's first general-purpose electronic digital computer, completed in 1945.",
    "The first computer mouse was made of wood.",
    "The world's first website was created by Sir Tim Berners-Lee in 1991.",
    "The world's first programmer's text editor was called 'ed' and was written by Ken Thompson.",
    "JavaScript was originally named 'Mocha' and later 'LiveScript' before becoming JavaScript.",
    "The '404 Not Found' error message is named after the HTTP status code 404, indicating that a requested resource could not be found on a server.",
    "The longest word that can be typed using only the left hand on a QWERTY keyboard is 'stewardesses.'",
    "The first video game was created in 1958 by physicist William Higinbotham and was called 'Tennis for Two.'",
    "The first computer was programmed using punch cards in the 19th century.",
    "The world's first computer programmer job advertisement was published in 1946.",
    "Alan Turing, a British mathematician and logician, is considered the father of theoretical computer science and artificial intelligence.",
    "The 'Ctrl+Alt+Delete' key combination used to restart a computer was originally intended to be a mistake-prevention mechanism.",
    "The first computer mouse had only one button.",
    "The 'QWERTY' keyboard layout was designed to prevent typewriter jams by placing commonly used keys far apart.",
    "The 'Fibonacci sequence' is a series of numbers in which each number is the sum of the two preceding ones.",
    "The concept of 'open-source' software allows the source code to be freely available and modifiable by anyone.",
    "The world's first computer animation was created in 1962 by Ivan Sutherland and was called 'Sketchpad.'",
    "The first ever domain name registered was 'symbolics.com' on March 15, 1985.",
    "The '@' symbol in email addresses was chosen by Ray Tomlinson, the inventor of email, to separate the username from the host name.",
    "The first computer virus for MS-DOS, named 'Michaelangelo,' was discovered in 1991.",
    "The term 'software engineering' was first used during the NATO Software Engineering Conference in 1968.",
    "The 'Shift' key on typewriters was originally used to shift the entire carriage, allowing access to uppercase letters.",
    "The '404 Not Found' error code originated from CERN, the birthplace of the World Wide Web, Room 404.",
    "The world's first hard drive, IBM Model 350, was released in 1956 and could store 5MB of data.",
    "The term 'byte' was coined by Werner Buchholz in 1956.",
    "The world's first computer game, 'OXO' (Noughts and Crosses), was created in 1952 by Alexander S. Douglas.",
    "Malware is a combination of the words 'malicious' and 'software.'",
    "The first digital computer, the Atanasoff-Berry Computer (ABC), was designed by John Atanasoff and Clifford Berry in the 1930s.",
    "HTML (Hypertext Markup Language) was first developed by Sir Tim Berners-Lee in the early 1990s.",
    "The first computer virus to infect Windows operating systems, 'Michaelangelo,' was discovered in 1991.",
    "The term 'debugging' originated from Grace Hopper removing a moth from a relay in the Harvard Mark II computer.",
    "Linux, an open-source operating system, was created by Linus Torvalds in 1991.",
    "The world's first computer programmer in the US was Augusta Ada King, Countess of Lovelace, also known as Ada Lovelace.",
    "The first computer mouse invented by Douglas Engelbart in 1964 was made of wood with two metal wheels.",
    "The first computer game to be commercially released was 'Computer Space' in 1971.",
    "The first computer bug was found in the Harvard Mark II computer in 1947.",
    "The 'Ctrl+Alt+Delete' key combination was originally intended to be a way to soft reboot a computer.",
    "The first known computer programmer was Ada Lovelace, who worked on Charles Babbage's Analytical Engine 0in the 1840s.",
    "The first computer mouse invented by Douglas Engelbart in 1964 was made of wood with two metal wheels.",
    "The first computer game to be commercially released was 'Computer Space' in 1971.",
    "The first computer bug was found in the Harvard Mark II computer in 1947.",
    "The term 'bug' to refer to a programming error originated from a moth that was found inside a computer in 1947 by Grace Hopper.",
    "The term 'byte' was coined by Werner Buchholz in 1956."
];

function getRandomJoke() {
    const jokeContainer = document.getElementById("joke-text");
    const randomIndex = Math.floor(Math.random() * jokes.length);
    jokeContainer.innerText = jokes[randomIndex];
}

function getRandomFact() {
    const factContainer = document.getElementById("fact-text");
    const randomIndex = Math.floor(Math.random() * facts.length);
    factContainer.innerText = facts[randomIndex];
}
